// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckrvkqdqoibhvuinyvii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrcnZrcWRxb2liaHZ1aW55dmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzU3NDAsImV4cCI6MjA2MzMxMTc0MH0.DFu4ossMwINSoYTvsk4XEgNeTqnFlthMKopIs_mrDck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);